language: node_js
node_js:
- iojs
sudo: false
env:
  matrix:
  - secure: pD+3SP+R5qSn4qEqql38nXiZiW1GWmLMUE4r89ozDWL8mSd+CgnA3TCTVQ5UFVylT94ntIrrD6XOacVsXfh68nzouAiGLuAE8+Ac1eVHUc9PkEk+CEU22KfNPfIr7nFHh068A7h6UElgmoeQVefl8w4GoRpyGewpsqB651gt3Zs=
  - secure: aNoO9332eotJpX7QWKFk0xuQoWOmEIhzZDDfivGqGD/rYUIhfmkW8MQGtISeabQIGPoNz/PcBbUuc9VsNbH4g6f6URw/RqsV5BwpUgTBGUIdi7VJDNUBeCFE3HCZp6wUX3DiNFBDaJ6dCPsnxc2czg2G3dTvNAM3+RW6I2CZRYw=
