language: node_js
node_js:
- '0.12'
env:
  matrix:
  - secure: TTdvh8YaiJSVBr8yXmwxpxNCih0RugZY1OKgD6I0oU4jvEY0VGHmoPxUOfxb68AGe7RlTHvz/Z7rrfjFUzyjEem/+8cotkyIfj0XsDMvBxlF52zYR0Ye1Y6hYinljprXxE7LrCrqDn3Pq7ZrhF3SAIBBwfKXS24Y1PuCdUPdv10=
  - secure: Xkq2wkSqAg+4gqR0rKpGvOMGdMQN1q+QoxMLysd1gXLCBKGGAVqfkKlBoLpz2i+p1wlF2/tVpCSuJgOmz5sYI59Ytn6VJE+lfhxsRqYtY5SAPWFihU+PL4LcWcnKOjJO3JxR254AorIzKiIjZcRWiCKSCHA9b37QaU+GhN4jtzc=
