language: node_js
node_js:
- iojs
sudo: false
env:
  global:
  - secure: cf2CyXX40VDXIQNzRwA+wxLjkaxQuV2DxnOOW5DdLBSxIJzdK+jKGPwI0wU2IW3Yj224AwHdQRLE//FvkPRsa8ei0FjWKx5q1Sr+IKBIox+TI9y6W42HQvzRQXO1y/7Xr71qB2kEgP7btjaGLKYn9kykU9aYbYQkILI/8t6cxng=
  - secure: EGTp3kPNIG6lsjdVZZHlrFlg2JkOe7PTkttpC5BC0iwmVMTQPzgzOUNpXhRvOQsl16sCZVjdfupAq0A33B7Z3uAYse5IO1n4m0WpZuNiClOJoLcpIqrPsXxlCOZi8EVhlUJLckX7GKXKCgu126P+bnbcoBKZzf7TvjQynJsbLN0=
